<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format2.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="2">
  <name>trosbag</name>
  <version>0.1.0</version>
  <description>
    Entry point for trosbag CLI tools (tros record / tros play)
  </description>
  <maintainer email="tros@d-robotics.com">D-Robotics</maintainer>
  <license>Apache License 2.0</license>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>ros2cli</exec_depend>
  <exec_depend>ros2bag</exec_depend>
  <exec_depend>rosbag2_py</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
